apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-test2-configmap
data:
  myvalue: "Hello World"
  drink: {{ quote .Values.favorite.drink }}
  food: {{ quote .Values.favorite.food }}
  name: {{ quote .Values.favorite.name }}
  fred: {{ quote .Values.fred }}