apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release2
  namespace: default
spec:
  install:
    disableWait: true
  upgrade:
    disableWait: true
  interval: 5m
  chart:
    spec:
      chart: ./test1
      sourceRef:
        kind: GitRepository
        name: my-config
        namespace: my-namespace
      interval: 1m
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: analytics-api
  #     valuesKey: values.yaml