apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: h3-release
  namespace: default
spec:
  install:
    disableWait: true
  upgrade:
    disableWait: true
  interval: 5m
  chart:
    spec:
      chart: ./test2
      sourceRef:
        kind: GitRepository
        name: my-config
        namespace: my-namespace
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: test
      # namespace: kube-system
      valuesKey: testdata
      targetPath: favorite\.name